### ISSUE TITLE
500 Unexpected Error for a nonexistent GTM Listener

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-common-python#1057]
**What did you do?**

Call the `exists` method for a nonexistent GTM Listener.

**What did you expect to see?**

`False`

**What did you see instead? Under which circumstances?**

I got a `500 Unexpected Error`.

```
Text: u'{"code":500,"message":"Specified listener does not exist","errorStack":[]}'
```

**Steps to reproduce the issue**

```
>>> from f5.bigip import ManagementRoot
>>> mgmt = ManagementRoot("x.x.x.x", "admin", "admin")

>>> print mgmt.tm.gtm.listeners.listener.exists(name='my_listener', partition='Common')
/home/erjac/ansible/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erjac/ansible/venv/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1054, in exists
    session.get(base_uri, **kwargs)
  File "/home/erjac/ansible/venv/local/lib/python2.7/site-packages/icontrol/session.py", line 272, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 500 Unexpected Error: Internal Server Error for uri: https://x.x.x.x:443/mgmt/tm/gtm/listener/~Common~my_listener
Text: u'{"code":500,"message":"Specified listener does not exist","errorStack":[]}'
```

If the listener is present, the  `exists` method returns `True` as expected.

```
>>> from f5.bigip import ManagementRoot
>>> mgmt = ManagementRoot("x.x.x.x", "admin", "admin")

>>> listener = mgmt.tm.gtm.listeners.listener.create(name='my_listener', partition='Common', address='10.10.1.1')
/home/erjac/ansible/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
>>> print mgmt.tm.gtm.listeners.listener.exists(name='my_listener', partition='Common')
/home/erjac/ansible/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
True
```

**Comment by caphrim007** [comment]
@erjac77 what version of bigip and f5-sdk is this?

**Comment by caphrim007** [comment]
i see it return a

```
u'{"code":400,"message":"Specified listener does not exist","errorStack":[],"apiError":26214401}'
```

on 12.1.2. Still not the right code though. It should be returning 404

**Comment by erjac77** [comment]
@caphrim007

bigip: 11.6.0
f5-sdk: 2.2.2

**Comment by caphrim007** [comment]
on 12.1.2 this appears to fix it for me.

Adding the following to the `class Listener(resource)` class to the following file

* `/home/erjac/ansible/venv/local/lib/python2.7/site-packages/f5/bigip/tm/gtm/listener.py`

```
    def exists(self, **kwargs):
        # This endpoint does not return status 404 if the GET request
        # does not find the resource. On one installation it returned
        # 400, and on another it returned 500
        try:
            super(Listener, self).exists(**kwargs)
        except iControlUnexpectedHTTPError as ex:
            if 'listener does not exist' in str(ex):
                return False
        return True
```

@erjac77 can you confirm whether this also addresses 11.6.0?

**Comment by erjac77** [comment]
I confirm, it works on 11.6.0.

Thanks again for your prompt response!

**Comment by caphrim007** [comment]
@erjac77 i will commit this fix in a moment. i'll close the issue when that happens
