### ISSUE TITLE
BigIq RegKey Device licensing API is broken

### ISSUE THREAD

**Issue by mindw** [F5Networks/f5-common-python#1107]
The following  code fails:
```
from f5.bigiq import ManagementRoot as bigiq_management_root

bigiq = bigiq_management_root(host, user, password) 
bigiq.cm.device.licensing.pool.regkey.licenses_s.get_collection()
licenses = bigiq.client.cm.device.licensing.pool.regkey.licenses_s.get_collection()
k, = licenses[0].offerings_s.get_collection()
k.members_s.get_collection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gabdav01/.virtualenvs/splatt/lib/python3.5/site-packages/f5/bigip/mixins.py", line 102, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigiq.cm.device.licensing.pool.regkey.licenses.Offering'>' object has no attribute 'members_s'
'<class 'f5.bigiq.cm.device.licensing.pool.regkey.licenses.Offering'>' object has no attribute 'members_s'
```
This is likely to be caused by missing 
```
        self._meta_data['allowed_lazy_attributes'] = [
            Members_s
        ]
```
in
https://github.com/F5Networks/f5-common-python/blob/development/f5/bigiq/cm/device/licensing/pool/regkey/licenses.py#L69

The reference iControl REST endpoint:
```
/mgmt/cm/device/licensing/pool/regkey/licenses/{id}/offerings/{key}/members
```

**Comment by caphrim007** [comment]
@mindw this should be fixed now
