### ISSUE TITLE
Unable to use the "exists" method for GTM Topology

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-common-python#1323]
Hi,

The exists method for GTM Topology records doesn't seem to work with a Datacenter as LDNS routing destination.

**_With the partition_** in the Datacenter's name, I get a "**_instance names and partitions cannot contain '/'_**" error message.
```
>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter /Common/DC1', partition='Common')       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1108, in exists
    return self._exists(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1120, in _exists
    session.get(base_uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 252, in wrapper
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 200, in generate_bigip_uri
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 168, in _validate_uri_parts
    _validate_name_partition_subpath(name)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 138, in _validate_name_partition_subpath
    raise InvalidInstanceNameOrFolder(error_message)
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/', but it's: ldns: country US server: datacenter /Common/DC1
```

**_Without the partition_** in the Datacenter's name, I get a "**_Topologies must specify both regions: ldns: server:_**" error message.
```
>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter DC1', partition='Common')        
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1108, in exists
    return self._exists(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1120, in _exists
    session.get(base_uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 272, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://172.16.227.35:21443/mgmt/tm/gtm/topology/~Common~ldns:%20country%20US%20server:%20datacenter%20DC1
Text: u'{"code":400,"message":"Topologies must specify both regions: ldns: server:","errorStack":[],"apiError":26214401}'
```

Surprisingly, it works for the create method.
```
>>> topo = mgmt.tm.gtm.topology_s.topology.create(name='ldns: country US server: datacenter /Common/DC1', partition='Common')
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

Versions:
- f5-sdk  -> 3.0.3
- BIG-IP -> 12.1.2

Thank you.

**Comment by wojtek0806** [comment]
i think i know what the issue is will do that this week

**Comment by erjac77** [comment]
@wojtek0806, Do you have any news on this?

**Comment by jasonrahm** [comment]
@erjac77 you can pull down my branch to test the fix: https://github.com/jasonrahm/f5-common-python/tree/bug.1323. It's working for me on my dev box but I'd like to get confirmation from you before merging to the development branch.

**Comment by erjac77** [comment]
@jasonrahm , unfortunately, it's not working in my case. The traces are slightly different.

```
>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter /Common/DC1', partition='Common')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/tm/gtm/topology.py", line 151, in exists
    return self._exists(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1120, in _exists
    session.get(base_uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 271, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://172.16.227.35:21443/mgmt/tm/gtm/topology/~Common~ldns:%20country%20US%20server:%20datacenter%20~Common~DC1
Text: u'{"code":400,"message":"Topologies must specify both regions: ldns: server:","errorStack":[],"apiError":26214401}'

>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter DC1', partition='Common')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/tm/gtm/topology.py", line 151, in exists
    return self._exists(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py", line 1120, in _exists
    session.get(base_uri, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 271, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://172.16.227.35:21443/mgmt/tm/gtm/topology/~Common~ldns:%20country%20US%20server:%20datacenter%20DC1
Text: u'{"code":400,"message":"Topologies must specify both regions: ldns: server:","errorStack":[],"apiError":26214401}'
```

I've only pulled 'topology.py' though. Did you make modifications elsewhere?

**Comment by jasonrahm** [comment]
let me drop to 12.1.2 and see if I get the same error

**Comment by jasonrahm** [comment]
Ok, so I will need to talk to the team on how to fix this (in a helpful way, see below) but the problem it's having is with you supplying the partition kwarg. If you remove that, the exists works fine.

Many of the GTM objects have to exist in /Common anyway, so there isn't a need for the partition argument anyway for ([see solution on AskF5](https://support.f5.com/csp/article/K01990709)):

- Data centers
- Servers
- Links
- Prober pools
- DNS zones
- DNS keys
- Regions

topology records don't have partition arguments at all, but the objects they reference do. So you can safely remove the partition argument on topology record requests.

**Comment by erjac77** [comment]
You're right. Works like a charm if I remove the partition argument.

```
>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter /Common/DC1')
>>> print topo
True
```

However, if I don't include the partition in the datacenter name, it returns false.

```
>>> topo = mgmt.tm.gtm.topology_s.topology.exists(name='ldns: country US server: datacenter DC1')
>>> print topo
False
```

**Comment by jasonrahm** [comment]
Yeah, it does need to match the record as stored in the config.

**Comment by erjac77** [comment]
Ok then. I was just wondering if it is something that the SDK should take care of...

Anyway, thanks for the fix!

**Comment by jasonrahm** [comment]
We’ll talk about how to handle that larger issue

**Comment by erjac77** [comment]
Sounds good to me. Thanks again for your help and Happy New Year!

**Comment by jasonrahm** [comment]
you bet, happy new year to you as well.
