### ISSUE TITLE
iControlUnexpectedHTTPError: 401 Unexpected Error: F5 Authorization Required for uri: https://10.50.2.65:443/mgmt/tm/sys/

### ISSUE THREAD

**Issue by kimoziiiii** [F5Networks/f5-common-python#1324]
* python:2.7
* sdk: f5-sdk 3.0.4
* f5 software: BIG-IP v11.6.1
* f5 user role: administrator

```
(py2.7env) root@ubuntu:~# ipython 
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from f5.bigip import ManagementRoot

In [2]: mgmt = ManagementRoot("10.50.2.65", "*****", "*****")
/root/py2.7env/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
---------------------------------------------------------------------------
iControlUnexpectedHTTPError               Traceback (most recent call last)
<ipython-input-2-0cb9e9db64a8> in <module>()
----> 1 mgmt = ManagementRoot("10.50.2.65", "*****", "*****")

/root/py2.7env/lib/python2.7/site-packages/f5/bigip/__init__.pyc in __init__(self, hostname, username, password, **kwargs)
    122         )
    123         self.set_metadata_uri(**self.args)
--> 124         self.post_configuration_setup()
    125 
    126     def set_metadata_uri(self, *args, **kwargs):

/root/py2.7env/lib/python2.7/site-packages/f5/bigip/__init__.pyc in post_configuration_setup(self)
     89 
     90     def post_configuration_setup(self):
---> 91         self._get_tmos_version()
     92 
     93     def _get_tmos_version(self):

/root/py2.7env/lib/python2.7/site-packages/f5/bigip/__init__.pyc in _get_tmos_version(self)
     94         connect = self._meta_data['bigip']._meta_data['icr_session']
     95         base_uri = self._meta_data['uri'] + 'tm/sys/'
---> 96         response = connect.get(base_uri)
     97         ver = response.json()
     98         version = urlparse.parse_qs(

/root/py2.7env/lib/python2.7/site-packages/icontrol/session.pyc in wrapper(self, RIC_base_uri, **kwargs)
    270                              response.url,
    271                              response.text)
--> 272             raise iControlUnexpectedHTTPError(error_message, response=response)
    273         return response
    274     return wrapper

iControlUnexpectedHTTPError: 401 Unexpected Error: F5 Authorization Required for uri: https://10.50.2.65:443/mgmt/tm/sys/
Text: u'{"code":401,"message":"Authorization failed: user=https://localhost/mgmt/shared/authz/users/hai.ping resource=/mgmt/tm/sys verb=GET uri:http://localhost:8100/mgmt/tm/sys/ referrer:10.60.9.95 sender:10.60.9.95","referer":"10.60.9.95","restOperationId":5407297,"errorStack":["java.lang.SecurityException: Authorization failed: user=https://localhost/mgmt/shared/authz/users/hai.ping resource=/mgmt/tm/sys verb=GET uri:http://localhost:8100/mgmt/tm/sys/ referrer:10.60.9.95 sender:10.60.9.95","at com.f5.rest.workers.ForwarderWorker.failPermissionValidation(ForwarderWorker.java:565)","at com.f5.rest.workers.ForwarderWorker.evaluateUserPermission(ForwarderWorker.java:633)","at com.f5.rest.workers.ForwarderWorker.evaluatePermission(ForwarderWorker.java:537)","at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:202)","at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:370)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1009)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:976)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:889)","at com.f5.rest.common.RestServer.access$000(RestServer.java:43)","at com.f5.rest.common.RestServer$1.run(RestServer.java:165)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:744)\\n"]}'
```
help..

**Comment by caphrim007** [comment]
@kimoziiiii I dont believe you can auth to an 11.6.1 device with this SDK.

**Comment by kimoziiiii** [comment]
@caphrim007 You mean this SDK not support 11.6.1 ?  this SDK support which version?

**Comment by caphrim007** [comment]
@kimoziiiii are you using tacacs or ldap to connect?

**Comment by kimoziiiii** [comment]
@caphrim007 use cisco aaa manage user account

**Comment by kimoziiiii** [comment]
@caphrim007 you mean this SDK only support local user?

**Comment by caphrim007** [comment]
@kimoziiiii try setting the `token=true` parameter in the `ManagementRoot` object instantiation

**Comment by kimoziiiii** [comment]
@caphrim007 when i use `token=True` parameter in the `ManagementRoot`, same error raise

**Comment by caphrim007** [comment]
@kimoziiiii what role does the remote role for this user have in the bigip?

**Comment by kimoziiiii** [comment]
`f5 user role: administrator`, pls check my question detail :)

**Comment by caphrim007** [comment]
@kimoziiiii do authentication success messages appear in /var/log/secure when you authenticate using this account?

**Comment by kimoziiiii** [comment]
@caphrim007  when i try to run `mgmt = ManagementRoot("10.50.2.65", "useid", "passw0rd")` in python, 
then i check `/var/log/secure` in F5, there is no records about this test.

**Comment by caphrim007** [comment]
@kimoziiiii that would suggest that remote authentication is not happening. If you run the same command with `token='tmos'` do you get the same error and lack of message in /var/log/secure ?

**Comment by kimoziiiii** [comment]
@caphrim007 yes, i got same error and lack of  message in /var/log/secure!

**Comment by caphrim007** [comment]
@kimoziiiii does the following work?

`curl -k -u user:pass https://10.50.2.65/mgmt/tm/sys`

replace user/pass with your username and password

**Comment by kimoziiiii** [comment]
@caphrim007 i have got a local admin account for test from f5 administrator . 
```bash
In [1]: from f5.bigip import ManagementRoot

In [2]: mgmt = ManagementRoot("10.50.2.65", "admin", "*******")
/root/py2.7env/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

In [3]: mgmt.
mgmt.args                      mgmt.icontrol_version          mgmt.post_configuration_setup  mgmt.set_metadata_uri          
mgmt.configure_meta_data       mgmt.icrs                      mgmt.raw                       mgmt.tmos_version              
mgmt.hostname                  mgmt.parse_arguments           mgmt.set_icr_metadata          mgmt.transform_attr_names      
In [4]: mgmt.tmos_version
Out[4]: u'11.6.1'
```
does it not support third-party certification?

**Comment by caphrim007** [comment]
@kimoziiiii not at this time.

**Comment by wojtek0806** [comment]
@kimoziiiii looks like @caphrim007 answered this closing
