### ISSUE TITLE
Version 3.0.6 gives RecursionError

### ISSUE THREAD

**Issue by Kyrremann** [F5Networks/f5-common-python#1339]
Version `3.0.6` of `f5-sdk`, gives me an `RecursionError` when I try to create a new ManagmentRoot. Version `3.0.5` works as expected.

```python
mgmt = ManagementRoot(bigip_server, bigip_username, bigip_password, token='tmos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$USER/.local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 152, in __init__
    self.post_configuration_setup()
  File "/home/$USER/.local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 111, in post_configuration_setup
    self._get_tmos_version()
  File "/home/$USER/.local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 120, in _get_tmos_version
    response = connect.get(base_uri)
  File "/home/$USER/.local/lib/python3.6/site-packages/icontrol/session.py", line 257, in wrapper
    response = method(self, REST_uri, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/icontrol/session.py", line 462, in get
    return self.session.get(uri, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/home/$USER/.local/lib/python3.6/site-packages/icontrol/authtoken.py", line 254, in __call__
    self.get_new_token(netloc)
  File "/home/$USER/.local/lib/python3.6/site-packages/icontrol/authtoken.py", line 150, in get_new_token
    auth=HTTPBasicAuth(self.username, self.password)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/$USER/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/$USER/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/$USER/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/$USER/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/$USER/.local/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/home/$USER/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 269, in create_urllib3_context
    context.options |= options
  File "/home/$USER/.pyenv/versions/3.6.2/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/home/$USER/.pyenv/versions/3.6.2/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/home/$USER/.pyenv/versions/3.6.2/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 316 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I'm running `Python 3.6.2` at the moment.

**Comment by caphrim007** [comment]
this doesnt look like an sdk error, it looks like something in the python openssl code, off the top of my head i'm not sure what would be causing this, but I will try to reproduce.

**Comment by caphrim007** [comment]
can you post the output of `pip freeze`?

**Comment by Kyrremann** [comment]
Output of freeze is:
```text
root@$USER-N501VW:/# pip freeze
certifi==2017.11.5
chardet==3.0.4
enum-compat==0.0.2
eventlet==0.21.0
f5-icontrol-rest==1.3.4
f5-sdk==3.0.6
greenlet==0.4.12
idna==2.6
requests==2.18.4
six==1.11.0
urllib3==1.22
```
Python code I use:
```python
from f5.bigip import ManagementRoot
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

BIGIP_URL = 'bigip.com'
BIGIP_USER = 'bigip_user'
BIGIP_PASSWORD = 'bigip_password'

mgmt = ManagementRoot(BIGIP_URL, BIGIP_USER, BIGIP_PASSWORD, token='tmos')
```

The problem may be that we don't have HTTPS/certificate on the server, hence the `disable_warnings`.

A complete example of it in Docker.
```bash
$ docker run --rm -it --network=host python:3.6.2 bash
root@$USER-N501VW:/# python --version
Python 3.6.2
root@$USER-N501VW:/# pip --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
root@$USER-N501VW:/# pip install f5-sdk
Collecting f5-sdk
  Downloading f5-sdk-3.0.6.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 1.5MB/s 
Collecting six>=1.9.0 (from f5-sdk)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting f5-icontrol-rest>=1.3.0 (from f5-sdk)
  Downloading f5-icontrol-rest-1.3.4.tar.gz
Collecting eventlet>=0.21.0 (from f5-sdk)
  Downloading eventlet-0.21.0-py2.py3-none-any.whl (403kB)
    100% |████████████████████████████████| 409kB 2.0MB/s 
Collecting requests<3,>=2.5.0 (from f5-icontrol-rest>=1.3.0->f5-sdk)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 12.9MB/s 
Collecting enum-compat (from eventlet>=0.21.0->f5-sdk)
  Downloading enum-compat-0.0.2.tar.gz
Collecting greenlet>=0.3 (from eventlet>=0.21.0->f5-sdk)
  Downloading greenlet-0.4.12-cp36-cp36m-manylinux1_x86_64.whl (42kB)
    100% |████████████████████████████████| 51kB 12.7MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests<3,>=2.5.0->f5-icontrol-rest>=1.3.0->f5-sdk)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.3MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests<3,>=2.5.0->f5-icontrol-rest>=1.3.0->f5-sdk)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 7.0MB/s 
Collecting certifi>=2017.4.17 (from requests<3,>=2.5.0->f5-icontrol-rest>=1.3.0->f5-sdk)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 3.8MB/s 
Collecting idna<2.7,>=2.5 (from requests<3,>=2.5.0->f5-icontrol-rest>=1.3.0->f5-sdk)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 10.6MB/s 
Building wheels for collected packages: f5-sdk, f5-icontrol-rest, enum-compat
  Running setup.py bdist_wheel for f5-sdk ... done
  Stored in directory: /root/.cache/pip/wheels/29/83/05/824755fa4a893850e490f145d60170e78daef68a72a7aba302
  Running setup.py bdist_wheel for f5-icontrol-rest ... done
  Stored in directory: /root/.cache/pip/wheels/d6/71/37/b82341aab14812da5e22292384a2a6d08732d57078484533c9
  Running setup.py bdist_wheel for enum-compat ... done
  Stored in directory: /root/.cache/pip/wheels/cb/f2/00/7616514d23c84bf58b7e9d034cdb7ff92f1b93c08b6a21ca8b
Successfully built f5-sdk f5-icontrol-rest enum-compat
Installing collected packages: six, chardet, urllib3, certifi, idna, requests, f5-icontrol-rest, enum-compat, greenlet, eventlet, f5-sdk
Successfully installed certifi-2017.11.5 chardet-3.0.4 enum-compat-0.0.2 eventlet-0.21.0 f5-icontrol-rest-1.3.4 f5-sdk-3.0.6 greenlet-0.4.12 idna-2.6 requests-2.18.4 six-1.11.0 urllib3-1.22
root@$USER-N501VW:/# pip freeze
certifi==2017.11.5
chardet==3.0.4
enum-compat==0.0.2
eventlet==0.21.0
f5-icontrol-rest==1.3.4
f5-sdk==3.0.6
greenlet==0.4.12
idna==2.6
requests==2.18.4
six==1.11.0
urllib3==1.22
root@$USER-N501VW:/# python
Python 3.6.2 (default, Sep 13 2017, 14:26:54) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from f5.bigip import ManagementRoot
>>> import urllib3
>>> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
>>> 
>>> BIGIP_URL = 'bigip.com'
>>> BIGIP_USER = 'bigip_user'
>>> BIGIP_PASSWORD = 'bigip_password'
>>> 
>>> mgmt = ManagementRoot(BIGIP_URL, BIGIP_USER, BIGIP_PASSWORD, token='tmos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 152, in __init__
    self.post_configuration_setup()
  File "/usr/local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 111, in post_configuration_setup
    self._get_tmos_version()
  File "/usr/local/lib/python3.6/site-packages/f5/bigip/__init__.py", line 120, in _get_tmos_version
    response = connect.get(base_uri)
  File "/usr/local/lib/python3.6/site-packages/icontrol/session.py", line 257, in wrapper
    response = method(self, REST_uri, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/icontrol/session.py", line 462, in get
    return self.session.get(uri, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.6/site-packages/icontrol/authtoken.py", line 254, in __call__
    self.get_new_token(netloc)
  File "/usr/local/lib/python3.6/site-packages/icontrol/authtoken.py", line 150, in get_new_token
    auth=HTTPBasicAuth(self.username, self.password)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 269, in create_urllib3_context
    context.options |= options
  File "/usr/local/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.6/ssl.py", line 459, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 316 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
>>>
```

**Comment by jasonrahm** [comment]
instead of importing urllib3, try importing requests:

import requests
requests.packages.urllib3.disable_warnings()

not sure if this is the same error, but I was never successful the other way

**Comment by caphrim007** [comment]
@Kyrremann in the event that it is related to eventlet, can you try pip installing from devel to ensure that you're not being bitten by that?

`pip install --upgrade git+https://github.com/F5Networks/f5-common-python.git`

**Comment by Kyrremann** [comment]
I fired up a new Docker container, and using the the devel-version it worked! So it looks like it's an eventlet problem.

**Comment by caphrim007** [comment]
@Kyrremann good to hear. the next release of the sdk will be next friday (the 22nd) US/PST

**Comment by jesmith18** [comment]
Installing pyOpenSSL eliminates this issue
