### ISSUE TITLE
SIGALRM doesn't exist on Windows

### ISSUE THREAD

**Issue by magnuswatn** [F5Networks/f5-common-python#1349]
SIGALRM doesn't exist on Windows, so after https://github.com/F5Networks/f5-common-python/pull/1341 bigip initialization failes on Windows:

```
>>> ManagementRoot('hei', 'hei', 'hei')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Run\Python\venvs\dynamisk-ipsperre-StKmWZ2n\lib\site-packages\f5\bigip\__init__.py", line 151, in __init__
    self.post_configuration_setup()
  File "C:\Run\Python\venvs\dynamisk-ipsperre-StKmWZ2n\lib\site-packages\f5\bigip\__init__.py", line 112, in post_config
uration_setup
    self._get_tmos_version()
  File "C:\Run\Python\venvs\dynamisk-ipsperre-StKmWZ2n\lib\site-packages\f5\bigip\__init__.py", line 118, in _get_tmos_v
ersion
    signal.signal(signal.SIGALRM, timeout_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

An easy fix would be to just try to explicit import SIGALRM together with signal (f5\bigip\__init__.py):
```
try:
    from signal import SIGALRM
    import signal
    HAS_SIGNAL = True
except ImportError:
    HAS_SIGNAL = False
```
This would of course disable this functionality on Windows, but I'm thinking that's not the end of the world?

Thanks.

**Comment by caphrim007** [comment]
thanks for the report. will fix
