### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by himalayanBuddy** [F5Networks/f5-common-python#1362]
I am using Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32.

f5-sdk 3.0.8

I get the following error message while trying to connect to BIG-IP.

Traceback (most recent call last):
  File "c:\Users\hpokh\Desktop\Python_Files\delete_pool.py", line 17, in <module>
    b = ManagementRoot(device_name, user_name, password)
  File "C:\Python27\lib\site-packages\f5\bigip\__init__.py", line 150, in __init__
    self.post_configuration_setup()
  File "C:\Python27\lib\site-packages\f5\bigip\__init__.py", line 111, in post_configuration_setup
    self._get_tmos_version()
  File "C:\Python27\lib\site-packages\f5\bigip\__init__.py", line 117, in _get_tmos_version
    signal.signal(signal.SIGALRM, timeout_handler)
AttributeError: 'module' object has no attribute 'SIGALRM'

**Comment by himalayanBuddy** [comment]
When I comment out the lines mentioned in the error it doesn't throw me error. When I try to get different stuffs get different error messages.

Traceback (most recent call last):
  File "c:\Users\hpokh\Desktop\Python_Files\delete_pool.py", line 19, in <module>
    print (b.tm.ltm.pools)
  File "C:\Python27\lib\site-packages\f5\bigip\mixins.py", line 113, in __getattr__
    container._check_supported_versions(container, attribute)
  File "C:\Python27\lib\site-packages\f5\bigip\mixins.py", line 125, in _check_supported_versions
    tmos_v = container._meta_data['bigip'].tmos_version
  File "C:\Python27\lib\site-packages\f5\bigip\mixins.py", line 102, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.ManagementRoot'>' object has no attribute 'tmos_version'


Can someone take a look into this.

**Comment by himalayanBuddy** [comment]
https://bugs.python.org/issue27735 looks like windows doesn't support SIGALRM I commented out and changed the following lines in the code at least it is working for me now.

     def _get_tmos_version(self):
        connect = self._meta_data['bigip']._meta_data['icr_session']
        base_uri = self._meta_data['uri'] + 'tm/sys/'
        # if HAS_SIGNAL:
            # signal.signal(signal.SIGALRM , timeout_handler)
            # #signal.alarm(int(self.args['timeout']))
            # response = connect.get(base_uri)
            # #signal.alarm(0)
        # else:

**Comment by caphrim007** [comment]
@harishpokharel this is fixed in devel and will be released with 3.0.9
