### ISSUE TITLE
Authentication Issue 401

### ISSUE THREAD

**Issue by jmcgrath207** [F5Networks/f5-common-python#1442]
I am having a issue where I keep on get 401 HTTP errors with a user even though I can log into the GUI and SSH. 

```python
from f5.bigip import ManagementRoot
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

# Connect to the BIG-IP
mgmt = ManagementRoot("1.1.1.1", "username", "password", verify=False)



Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/apps/CSFI/.python/lib/python3.6/site-packages/f5/bigip/__init__.py", line 168, in __init__
    self.post_configuration_setup()
  File "/apps/CSFI/.python/lib/python3.6/site-packages/f5/bigip/__init__.py", line 114, in post_configuration_setup
    self._get_tmos_version()
  File "/apps/CSFI/.python/lib/python3.6/site-packages/f5/bigip/__init__.py", line 122, in _get_tmos_version
    response = connect.get(base_uri)
  File "/apps/CSFI/.python/lib/python3.6/site-packages/icontrol/session.py", line 284, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.exceptions.iControlUnexpectedHTTPError: 401 Unexpected Error: F5 Authorization Required for uri: https://1.1.1.1:443/mgmt/tm/sys/
```

Here are the details about the User and the BigIP version that is running

```bash
# tmsh list auth user all

 auth user username {
    description "username"
    encrypted-password ""
    partition Common
    partition-access all
    role resource-admin
    shell bash
}

# tmsh show /sys version

Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.3
  Build    0.0.163
  Edition  Final
  Date     Wed Apr 22 16:32:47 PDT 2015

```

**Comment by caphrim007** [comment]
@jmcgrath207 

are you logging in with the username 'admin'? If not, then it won't work on the version of BIGIP that you have. generally speaking the REST API doesn't "work" until 12.0.0 at the earliest

**Comment by jmcgrath207** [comment]
yeah, the username is not named `admin` . Well, that sucks. Thanks for taking a look at this @caphrim007 .
