### ISSUE TITLE
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/' - interface names with a '/' cannot be referenced

### ISSUE THREAD

**Issue by ghost** [F5Networks/f5-common-python#1558]
I am using  f5-sdk (3.0.2) and importing ManagementRoot. I'm attempting to query an interface on a Viprion and it's erring because of the '/' in the interface name.

Here is the code snippet:
 
from f5.bigip import ManagementRoot
mgmt = ManagementRoot('192.168.1.1','admin', 'admin', timeout = 5)
interface = '1/3.0'
interface = mgmt.tm.net.interfaces.interface.load(name=interface)
print(interface)
 
This fails when its run against a viprion with following error:
 
(robot) [admin@myserver robot-f5]$ python run_test.py
Traceback (most recent call last):
  File "run_test.py", line 21, in <module>
    interface = mgmt.tm.net.interfaces.interface.load(name=interface)
  File "/home/admin/robot/lib64/python3.6/site-packages/f5/bigip/resource.py", line 1110, in load
    return self._load(**kwargs)
  File "/home/admin/robot/lib64/python3.6/site-packages/f5/bigip/resource.py", line 1084, in _load
    response = refresh_session.get(base_uri, **kwargs)
  File "/home/admin/robot/lib64/python3.6/site-packages/icontrol/session.py", line 273, in wrapper
    **kwargs)
  File "/home/admin/robot/lib64/python3.6/site-packages/icontrol/session.py", line 216, in generate_bigip_uri
    **kwargs)
  File "/home/admin/robot/lib64/python3.6/site-packages/icontrol/session.py", line 183, in _validate_uri_parts
    _validate_name_partition_subpath(name)
  File "/home/admin/robot/lib64/python3.6/site-packages/icontrol/session.py", line 153, in _validate_name_partition_subpath
    raise InvalidInstanceNameOrFolder(error_message)
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/', but it's: 1/3.0

**Comment by f5-rahm** [comment]
Add the transform_name=True kwarg and see if that helps.

**Comment by ghost** [comment]
That worked! Sorry, I see that a similar issue had been posted before but I appreciate the help!
