### ISSUE TITLE
Update the requirements to use f5-icontrol-rest >= 1.0.3

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-common-python#280]
There was a bug that was fixed in 1.0.3 with F5Networks/f5-icontrol-rest#59 that we need to ensure we have to avoid the library opening too many files.

**Comment by harishpokharel** [comment]
Still getting the error after rest upgrade:

Traceback (most recent call last):
  File ".\f5_sdk_pool.py", line 11, in <module>
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 403, in get_collection
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 281, in refresh
  File "C:\Python27\lib\site-packages\f5\bigip\resource.py", line 264, in _refresh
  File "C:\Python27\lib\site-packages\icontrol\session.py", line 274, in wrapper
  File "C:\Python27\lib\site-packages\icontrol\session.py", line 229, in _log_HTTP_verb_method_precall
  File "C:\Python27\lib\logging\__init__.py", line 1223, in log
  File "C:\Python27\lib\logging\__init__.py", line 1278, in _log
  File "C:\Python27\lib\logging\__init__.py", line 1288, in handle
  File "C:\Python27\lib\logging\__init__.py", line 1328, in callHandlers
  File "C:\Python27\lib\logging\__init__.py", line 751, in handle
  File "C:\Python27\lib\logging\__init__.py", line 948, in emit
  File "C:\Python27\lib\logging\__init__.py", line 935, in _open
IOError: [Errno 24] Too many open files: 'C:\\Users\\hpokhare\\Desktop\\python27_Scripts\\logs\\iControlRESTSession\\145
8157364\\get'
