### ISSUE TITLE
Unable to use "exists" for a route that contains "/" in the name

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-common-python#543]
Unable to use "exists" for a route that contains "/" in the name.  This should be a valid resource name (the GUI has no issues).

The issue looks like it is in the underlying iControl library, but here's the steps to reproduce:

```
cat route_exists.py
from f5.bigip import ManagementRoot

mgmt = ManagementRoot('10.1.1.2','admin','admin')
mgmt.tm.net.routes.route.exists(name='172.16.31.0/24',partition='Common')
$ python route_exists.py
...
Traceback (most recent call last):
  File "route_exists.py", line 4, in <module>
    mgmt.tm.net.routes.route.exists(name='172.16.31.0/24',partition='Common')
  File "/home/user/projects/test/0.1.9/local/lib/python2.7/site-packages/f5_sdk-1.0.0-py2.7.egg/f5/bigip/resource.py", line 894, in exists
    session.get(base_uri, **kwargs)
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 210, in wrapper
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 174, in generate_bigip_uri
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 148, in _validate_uri_parts
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 122, in _validate_name_or_partition
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/', but it's: 172.16.31.0/24
$ cat check_route.py
from icontrol.session import iControlRESTSession
import requests
try:
    requests.packages.urllib3.disable_warnings()
except:
    pass

icr_session = iControlRESTSession('admin', 'admin',timeout=3600)
uri = 'https://10.1.1.2:443/mgmt/tm/net/route/'
name = '172.16.31.0/24'
partition = 'Common'
r = icr_session.get(
    uri,
    name=name,
    partition=partition)
print r.status_code
r = icr_session.get(
    uri,
    name=name,
    partition=partition,
    uri_as_parts = True)
print r.status_code

$ python check_route.py
200
Traceback (most recent call last):
  File "check_route.py", line 21, in <module>
    uri_as_parts = True)
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 210, in wrapper
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 174, in generate_bigip_uri
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 148, in _validate_uri_parts
  File "build/bdist.linux-x86_64/egg/icontrol/session.py", line 122, in _validate_name_or_partition
icontrol.exceptions.InvalidInstanceNameOrFolder: instance names and partitions cannot contain '/', but it's: 172.16.31.0/24

```

**Comment by jasonrahm** [comment]
i can't create a route with name including a "/" in the GUI, I get an error: 

**01070734:3: Configuration error: Can't associate static route (/Common/192.168.22.0/24) folder does not exist**

Given the special nature of the "/" for bigip objects I do not think we should support this. My $.02.

**Comment by chen23** [comment]
I just tried via the GUI and can confirm it doesn't work there.  Looks like TMSH / REST API will allow it.

**Comment by zancas** [comment]
I agree with @jasonrahm .
