### ISSUE TITLE
Invalid state when updating a pool and pool member?

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-common-python#985]
this needs investigating as per comment in #840

**Comment by erjac77** [comment]
@wojtek0806 

Without a monitor:
```
>>> mypool = mgmt.tm.ltm.pools.pool.create(name='mypool', partition='Common')
>>> m1 = mypool.members_s.members.create(partition='Common', name='10.10.10.112:80')
>>> m1.description = "new member"
>>> m1.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erjac/ansible/venv/local/lib/python2.7/site-packages/f5/bigip/tm/ltm/pool.py", line 98, in update
    raise MemberStateAlwaysRequiredOnUpdate(error_message)
f5.sdk_exception.MemberStateAlwaysRequiredOnUpdate: You must supply a value to the "state" parameter if you do not wish to change the state then pass "state=None".
>>> print m1.state
unchecked
```

With a monitor:
```
>>> mypool = mgmt.tm.ltm.pools.pool.create(name='mypool', partition='Common', monitor='http')
>>> m1 = mypool.members_s.members.create(partition='Common', name='10.10.10.112:80')
>>> m1.description = "new member"
>>> m1.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erjac/ansible/venv/local/lib/python2.7/site-packages/f5/bigip/tm/ltm/pool.py", line 98, in update
    raise MemberStateAlwaysRequiredOnUpdate(error_message)
f5.sdk_exception.MemberStateAlwaysRequiredOnUpdate: You must supply a value to the "state" parameter if you do not wish to change the state then pass "state=None".
>>> print m1.state
checking
```

With state set to None:
```
>>> mypool = mgmt.tm.ltm.pools.pool.create(name='mypool', partition='Common', monitor='http')
>>> m1 = mypool.members_s.members.create(partition='Common', name='10.10.10.112:80')
>>> m1.description = "new member"
>>> m1.state = None
>>> m1.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erjac/ansible/venv/local/lib/python2.7/site-packages/f5/bigip/tm/ltm/pool.py", line 98, in update
    raise MemberStateAlwaysRequiredOnUpdate(error_message)
f5.sdk_exception.MemberStateAlwaysRequiredOnUpdate: You must supply a value to the "state" parameter if you do not wish to change the state then pass "state=None".
>>> print m1.state
None
```

**Comment by wojtek0806** [comment]
@erjac77 the changes will be merged soon, feel free to test with my pool_fix branch.

**Comment by wojtek0806** [comment]
Some jsons for completenes:

With Monitor:

GUI State: Disabled
````
{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 1,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "user-disabled",
      "state": "down"
    }
  ]
}
````

GUI State: Enabled
````

{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 3658,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "monitor-enabled",
      "state": "down"
    }
  ]
}
````

GUI State: Forced-Offline
````
{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 3660,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "user-disabled",
      "state": "user-down"
    }
  ]
}
````

Without Monitor:

GUI State: Forced-Offline

````
{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 3660,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "user-disabled",
      "state": "user-down"
    }
  ]
}
````

GUI State: Disabled
````
{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 3663,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "user-disabled",
      "state": "unchecked"
    }
  ]
}
````

GUI State: Enabled

````
{
  "kind": "tm:ltm:pool:members:memberscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members?ver=11.6.0",
  "items": [
    {
      "kind": "tm:ltm:pool:members:membersstate",
      "name": "1.1.1.1:80",
      "partition": "Common",
      "fullPath": "/Common/1.1.1.1:80",
      "generation": 3665,
      "selfLink": "https://localhost/mgmt/tm/ltm/pool/~Common~test_pool/members/~Common~1.1.1.1:80?ver=11.6.0",
      "address": "1.1.1.1",
      "connectionLimit": 0,
      "dynamicRatio": 1,
      "ephemeral": "false",
      "fqdn": {
        "autopopulate": "disabled"
      },
      "inheritProfile": "enabled",
      "logging": "disabled",
      "monitor": "default",
      "priorityGroup": 0,
      "rateLimit": "disabled",
      "ratio": 1,
      "session": "user-enabled",
      "state": "unchecked"
    }
  ]
}
````
